//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_NetCore.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DetailGroup
    {
        public DetailGroup()
        {
            this.DetailItem = new HashSet<DetailItem>();
        }
    
        public int DetailGroupId { get; set; }

        public string Name { get; set; }

        public int ProductGroupId { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }

        public virtual ICollection<DetailItem> DetailItem { get; set; }

    }
}
