//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_NetCore.DomainClasses
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    [DisplayName("اخبار")]
    public partial class News : BaseEntity
    {
        public News()
        {
            this.NewsGallery = new HashSet<NewsGallery>();
            this.NewsTag = new HashSet<NewsTag>();
        }
    
        public int NewsId { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [Display(Name = "گروه خبری")]
        public int NewsGroupId { get; set; }

        [Display(Name = "عنوان خبر")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string NewsTitle { get; set; }

        [Display(Name = "توضیحات محصول")]
        //[AllowHtml]
        [DataType(DataType.MultilineText)]
        public string NewsDescription { get; set; }

        [Display(Name = "تصویر محصول")]
        [StringLength(150, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string NewsImage { get; set; }

        public int UserId { get; set; }

        [Display(Name = "نام مستعار")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [StringLength(150, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        //[Remote("Uniquealias", "News", ErrorMessage = "این نام قبلا گرفته شده است، لطفا نام دیگری انتخاب کنید!", AdditionalFields = "NewsID")]
        public string AliasName { get; set; }
    
        public virtual ICollection<NewsGallery> NewsGallery { get; set; }
        public virtual NewsGroup NewsGroup { get; set; }
        public virtual ICollection<NewsTag> NewsTag { get; set; }
        public virtual User User { get; set; }
    }
}
